spin_version = "1"
authors = ["Mikkel Mørk Hegnhøj <mikkel@fermyon.com>"]
description = ""
name = "click"
trigger = { type = "http", base = "/" }
version = "0.1.0"

# Please note the ordering of components is important. Root components MUST be first.
[[component]]
files  = [{ source = "frontend/", destination = "/" }]
id     = "fileserver"
source = "modules/spin_static_fs.wasm"
[component.trigger]
route = "/..."

[[component]]
id = "click"
source = "target/wasm32-wasi/release/click.wasm"
environment = { REDIS_ADDRESS = "redis://USERNAME:PASSWORD@REDIS_SERVER.cloud.redislabs.com:PORT" }
[component.trigger]
route = "/api"
[component.build]
command = "cargo build --target wasm32-wasi --release"